### ISSUE TITLE
RFE: sendMessage add support to pass an xunit file as parameter

### ISSUE THREAD

**Issue by bgoncalv** [fedora-ci/jenkins-pipeline-library#11]
sendMessage currently supports testingFarmResult, but some pipelines might not use testing farm, it would be nice if the function could support passing an xunit file as parameter.

**Comment by msrb** [comment]
This is a really good idea. I don't remember why I went with the full testing farm response map, but having just xunit passed as a param seems to be sufficient for the sendMessage purposes.

**Comment by msrb** [comment]
https://github.com/fedora-ci/jenkins-pipeline-library/pull/15
