### ISSUE TITLE
RFE: sendMessage add support to ci messages for pull requests

### ISSUE THREAD

**Issue by bgoncalv** [fedora-ci/jenkins-pipeline-library#12]
The function should be able to send message for pull requests.

example of messages:
https://apps.fedoraproject.org/datagrepper/id?id=2020-01a0ec44-c2f6-4f22-9f6c-6b01f0d34c76&is_raw=true&size=extra-large

https://apps.fedoraproject.org/datagrepper/id?id=2020-9ccdeaa3-88a4-45b5-aff4-ebdd982ab554&is_raw=true&size=extra-large

**Comment by bgoncalv** [comment]
These are the messages we use to trigger for PR, the messages pagure send already contains all the information needed to send a message.
 
New PR:
https://apps.fedoraproject.org/datagrepper/id?id=2020-f601a505-bd81-4b7b-baad-4f9f2191f82f&is_raw=true&size=extra-large
    
New comment:
https://apps.fedoraproject.org/datagrepper/id?id=2020-2b5f5b00-d9d8-4c4b-a527-20e377e76fd1&is_raw=true&size=extra-large

**Comment by msrb** [comment]
I *think* the `uid` field is the real unique identifier of this artifact type.

**Comment by bgoncalv** [comment]
It depends for what do you need this unique information. It is unique as each PR has an unique uid, but in case there is a new commit or rebase the uid will continue to be the same although the PR changed...

**Comment by msrb** [comment]
Support for PRs is already implemented -- I just forgot to close this issue :)
