### ISSUE TITLE
pipeline.id from ci messafe field should be the same even if message is sent on different jenkins job

### ISSUE THREAD

**Issue by bgoncalv** [fedora-ci/jenkins-pipeline-library#19]
The current code generates id based on jenkins job name. This causes s problem if for example the `queue` topic is sent by a trigger jenkins job and `running`/`complete` by a different job.

https://github.com/fedora-ci/jenkins-pipeline-library/blob/master/src/org/fedoraproject/jenkins/messages/RpmBuildMessageBuilder.groovy#L42

**Comment by msrb** [comment]
Already fixed, closing ;)
