### ISSUE TITLE
Please add 'source' entry

### ISSUE THREAD

**Issue by Andrei-Stepanov** [fedora-ci/jenkins-pipeline-library#38]
https://pagure.io/fedora-ci/messages/blob/master/f/schemas/rpm-build.yaml

https://apps.fedoraproject.org/datagrepper/id?id=2021-353ec68c-7117-4332-9298-2fe2ed515055&is_raw=true&size=extra-large

https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/33755/console

No entry `source`.

It is not required, but good to have.

**Comment by msrb** [comment]
Sure thing: https://github.com/fedora-ci/jenkins-pipeline-library/pull/45

**Comment by msrb** [comment]
The field is already available in "complete" messages, and with this patch it will appear also in "running" and "error". But only after the new code is promoted to production.
