### ISSUE TITLE
setBuildNameFromArtifactId throws exception on bad artifactId

### ISSUE THREAD

**Issue by bookwar** [fedora-ci/jenkins-pipeline-library#5]
### Issue
Currently setBuildNameFromArtifactId throws exception when artifactId has wrong format or is not associated with a real koji task-id.

### Expected

Meaningful error message

### Suggestion

Relax the requirement: if function cannot parse artifactID to get more info, use it as is.

**Comment by msrb** [comment]
PR: https://github.com/fedora-ci/jenkins-pipeline-library/pull/10

**Comment by msrb** [comment]
The PR is merged.
